// TEMPORARY AUTOGENERATED FILE: tinyjson stub code to make the package
// compilable during generation.

package  main

import (
  "github.com/CosmWasm/tinyjson/jwriter"
  "github.com/CosmWasm/tinyjson/jlexer"
)

func ( CreatePoolParams ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* CreatePoolParams ) UnmarshalJSON([]byte) error { return nil }
func ( CreatePoolParams ) MarshalTinyJSON(w *jwriter.Writer) {}
func (* CreatePoolParams ) UnmarshalTinyJSON(l *jlexer.Lexer) {}

type TinyJSON_exporter_CreatePoolParams *CreatePoolParams

func ( DexInstruction ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* DexInstruction ) UnmarshalJSON([]byte) error { return nil }
func ( DexInstruction ) MarshalTinyJSON(w *jwriter.Writer) {}
func (* DexInstruction ) UnmarshalTinyJSON(l *jlexer.Lexer) {}

type TinyJSON_exporter_DexInstruction *DexInstruction

func ( PoolInfo ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PoolInfo ) UnmarshalJSON([]byte) error { return nil }
func ( PoolInfo ) MarshalTinyJSON(w *jwriter.Writer) {}
func (* PoolInfo ) UnmarshalTinyJSON(l *jlexer.Lexer) {}

type TinyJSON_exporter_PoolInfo *PoolInfo

func ( ReturnAddress ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* ReturnAddress ) UnmarshalJSON([]byte) error { return nil }
func ( ReturnAddress ) MarshalTinyJSON(w *jwriter.Writer) {}
func (* ReturnAddress ) UnmarshalTinyJSON(l *jlexer.Lexer) {}

type TinyJSON_exporter_ReturnAddress *ReturnAddress
